<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjvAGZz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjvAGZz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFjvAGZz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFjvAGZz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFjvAGZz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FjvAGZz',
    'container.build_id' => 'e994bf06',
    'container.build_time' => 1563961378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjvAGZz');
