<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0ID9Bs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0ID9Bs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA0ID9Bs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA0ID9Bs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA0ID9Bs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A0ID9Bs',
    'container.build_id' => '981d47d8',
    'container.build_time' => 1563969853,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0ID9Bs');
